### PR TITLE
Added gitignore at root of directory. 

### PR DESCRIPTION
**Pull request by allisonabinger**
This will go to root of directory, then will be applied to all branches later.

### CODE REVIEW

**Review by kier-ious — APPROVED** [review]
ayo, looks great!

**Comment by Mariahseggebruch** [comment]
looks good.

**Review by Mariahseggebruch — APPROVED** [review]
Look's good

**Review by chris85gillis — COMMENTED** [review]
Giving you approval. :)

**Review by chris85gillis — APPROVED** [review]
Good work :)

**Review by marktipton — APPROVED** [review]
looks good

**Pull request merged**
